# Numpy
## 什麼是Numpy?
![](https://i.imgur.com/X0pj3xu.png)

## 複習 List

In [56]:
lst1 = [1, 2, 3, 4]
lst2 = [5, 6, 7, 8]
print(lst1, lst2)

[1, 2, 3, 4] [5, 6, 7, 8]


## 建立Numpy 陣列

In [57]:
import numpy as np
np1 = np.array(lst1) 
np1

array([1, 2, 3, 4])

## 觀察陣資料型態

In [58]:
np1.dtype #陣列中的型態必須一致 

dtype('int64')

## 轉換資料型態

In [59]:
tmp = np1.astype(np.float64)
tmp.dtype

dtype('float64')

## 陣列運算
lst1 = [1, 2, 3, 4]<br>lst2 = [5, 6, 7, 8]

In [61]:
np1*2

array([2, 4, 6, 8])

In [62]:
np2 = np.array(lst2)
np1 + np2

array([ 6,  8, 10, 12])

In [63]:
np1*np2

array([ 5, 12, 21, 32])

## 陣列中取值和定義新的數值
lst1 = [1, 2, 3, 4]<br>lst2 = [5, 6, 7, 8]

In [64]:
np1[1]

2

In [65]:
np1[1:3]

array([2, 3])

In [66]:
np1[1:]

array([2, 3, 4])

In [67]:
np1[-1]

4

In [69]:
np1[0] = 18
np1
np1[0] = 1

## 將一維陣列改為二維陣列
矩陣

In [70]:
np1 = np1.reshape((2,2))
np1

array([[1, 2],
       [3, 4]])

In [71]:
np2 = np2.reshape((2,2))
np2

array([[5, 6],
       [7, 8]])

## 矩陣相乘
![](https://i.imgur.com/DLAVQD1.png)

In [72]:
np1.dot(np2)

array([[19, 22],
       [43, 50]])